version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --dir file:///migrations
      --url postgres://admin:admin@db:5432/postgres?sslmode=disable
      --allow-dirty
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
