version: "3"

silent: true

tasks:
  run-dev:
    desc: Run the application in development mode
    cmds:
      - docker compose up -d
      - go run cmd/main.go

  lint:
    desc: Run the linter
    cmds:
      - golangci-lint run
