version: "3"

silent: true

tasks:
  run-dev:
    desc: Run the application in development mode
    cmds:
      - docker compose up -d
      - go run go/cmd/main.go

  lint:
    desc: Run the linter
    cmds:
      - golangci-lint run
      - sqlfluff lint go/schema.sql go/queries/ --dialect postgres

  fmt:
    desc: Format the code
    cmds:
      - sqlfluff fix go/schema.sql go/queries/ --dialect postgres

  create-migration:
    desc: Create a new migration
    cmds:
      - atlas migrate diff --config go/atlas.hcl {{.CLI_ARGS}} --env local

  migrate:
    desc: Run the migrations
    cmds:
      - atlas migrate apply --config go/atlas.hcl --env local
