version: "3"

silent: true

includes:
  go:
    taskfile: ./go/Taskfile.go.yaml
    dir: ./go
  o11y:
    taskfile: ./o11y/Taskfile.o11y.yaml
    dir: ./o11y

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  run-dev:
    aliases:
      - rd
    desc: Run the application in development mode
    cmd: docker compose up -d && task go:run-dev
  
  run-down:
    aliases:
      - rd
    desc: Run the application in development mode
    cmd: docker compose down

  lint:
    aliases:
      - l
    desc: Run the linter
    cmd: task go:lint

  fmt:
    aliases:
      - f
    desc: Format the code
    cmd: task go:fmt && task o11y:fmt

  create-migration:
    aliases:
      - cm
    desc: Create a new migration
    cmd: task go:create-migration

  migrate:
    aliases:
      - m
    desc: Run the migrations
    cmd: task go:migrate

