// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int32            `json:"id"`
	AccountName string           `json:"account_name"`
	Passhash    string           `json:"passhash"`
	Authority   bool             `json:"authority"`
	DelFlg      bool             `json:"del_flg"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
