// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context) ([]GetUserRow, error)
	Healthcheck(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
