name: Lint

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0


      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh
          sudo mv ./bin/golangci-lint /usr/local/bin

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Verify golangci-lint installation
        run: golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint

      # - name: Run sqlfluff
      #   run: sqlfluff lint schema.sql --dialect postgres
